server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
# Host system logs
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

# Docker container logs
- job_name: docker
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 10s
  relabel_configs:
    - source_labels: [__meta_docker_container_name]
      target_label: container
    - source_labels: [__meta_docker_container_image]
      target_label: image
    - source_labels: [__meta_docker_container_id]
      target_label: container_id

