services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: devops786
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - internal

  db:
    image: mariadb:latest
    container_name: wordpress_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: devops786
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: devops786
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html:ro
      - ../reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - internal

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
    networks:
      - internal

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - internal

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - internal

  grafana:
    image: grafana/grafana:9.5.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ../monitoring/grafana-provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - internal

  loki:
    image: grafana/loki:3.5.4
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ../logging/loki-data:/loki
      - ../logging/loki-config.yml:/etc/loki/local-config.yml:ro
    ports:
      - "3100:3100"
      - "9096:9096"
    networks:
      - internal

  promtail:
    image: grafana/promtail:3.5.4
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ../logging/promtail-config.yml:/etc/promtail/promtail.yml:ro
    networks:
      - internal

volumes:
  wordpress_data:
  db_data:
  grafana_data:

networks:
  internal:
    driver: bridge

